"""Module containing the `daterange` class."""

from datetime import date
from typing import Iterator, Literal, NoReturn, Sequence, SupportsIndex, final, overload

@final
class daterange (Sequence[date]):
  """Class designed to function just like range(), except iterating over date objects, rather than integers."""
  @overload
  def __init__ (self, start: date|str, stop: date|str, step = 1, /) -> None: ...
  @overload
  def __init__ (self, start: date|str, numdays: int, step = 1, /) -> None: ...
  @overload
  def __init__ (self, numdays: int, stop: date|str, step = 1, /) -> None: ...

  @overload
  def count (self, value: date|str, /) -> Literal[0,1]:
    """Counts the occurrences of the provided value."""
  @overload
  def count (self, value, /) -> Literal[0]: ...
  @overload
  def index (self, value: date|str, /) -> SupportsIndex:
    """Returns the index of the provided value, such that `daterange[daterange.index(x)] == x` is always `True`. Raises a `ValueError` if the provided value is not contained by this range."""
  @overload
  def index (self, value, /) -> NoReturn: ...

  def __len__ (self) -> int: ...
  def __iter__ (self) -> Iterator[date]: ...
  @overload
  def __getitem__ (self, index: SupportsIndex, /) -> date: ...
  @overload
  def __getitem__ (self, slice: slice, /) -> daterange: ...
  @overload
  def __contains__ (self, value: date|str, /) -> bool: ...
  @overload
  def __contains__ (self, value, /) -> Literal[False]: ...

  def __repr__ (self) -> str: ...
  def __hash__ (self) -> int: ...

  @overload
  def __eq__ (self, value: daterange, /) -> bool: ...
  @overload
  def __eq__ (self, value, /) -> Literal[False]: ...
