"""Module for the `TimeDeltaTuple` class."""

from datetime import timedelta
from typing import Literal, NamedTuple, overload

class TimeDeltaTuple (NamedTuple):
  """Class for representing timedeltas as sums of distinct measures."""
  dd: int = 0
  hh: int = 0
  mm: int = 0
  ss: int = 0
  ms: int = 0
  us: int = 0

  @property
  def days (self) -> int: ...
  @property
  def hours (self) -> int: ...
  @property
  def minutes (self) -> int: ...
  @property
  def seconds (self) -> int: ...
  @property
  def milliseconds (self) -> int: ...
  @property
  def microseconds (self) -> int: ...

  def asdays (self) -> float: ...
  def ashours (self) -> float: ...
  def asminutes (self) -> float: ...
  def asseconds (self) -> float: ...
  def asmilliseconds (self) -> float: ...
  def asmicroseconds (self) -> int: ...
  def astimedelta (self) -> timedelta: ...

  @classmethod
  def new (self, timedelta: timedelta, /) -> TimeDeltaTuple: ...

  def __str__ (self) -> str: ...

  @overload
  def __eq__ (self, value: TimeDeltaTuple|timedelta, /) -> bool: ...
  @overload
  def __eq__ (self, value, /) -> Literal[False]: ...

  def __abs__ (self) -> TimeDeltaTuple: ...
